# version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8878:80
    depends_on:
      - db
    container_name: project1_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: project1_app
#   db:
#     image: mysql:8.0
#     restart: always
#     volumes:
#        - ./tmp/db:/var/lib/mysql
#     environment:
#         MYSQL_DATABASE: lardocker_25.04.25
#         MYSQL_ROOT_PASSWORD: root
#     ports:
#       - 8101:3306
#     command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
#     container_name: project_db

